/* --- EVA15風 演出の宣言データ --- */

// ============================================================
// trust: 信頼度（%）。通常時はでちゃう！「新世紀エヴァンゲリオン〜未来への咆哮〜」演出信頼度特集の
//        ノーマルモード、ST はパチ７「【演出信頼度まとめ】新世紀エヴァンゲリオン～未来への咆哮～」の
//        IMPACT MODE（レイモード以外＝シンジモード）の値。100 は濃厚
//        （only で確変種別に絞れば確変濃厚、r10 だけなら 10R確変濃厚）。
//        当該レバブルはシミュ専用の値。
// share: 「単独で出たとき当りの何%を占めるか」の重み（実機非公開の推定値。ここだけ触れば調整できる）。
//        当り確率を固定するため、信頼度 100% 未満の演出は読み込み時に一律で縮められる
//        （eva-engine.js の alpha）。信頼度 100% の演出と fixed: true の演出は縮めない
//        ＝ほぼそのまま当りの share% になる。
// rate: リーチが決まった後の出現率（SP リーチに必ず付く部品の層だけ）。数値かリーチ id ごとの表。
// forceKakuhen: この演出で当ったら 3R確変（シンクロ経由の暴走ボーナス）。
// spBoost: その層の演出が SP リーチの回転で何倍出やすいか（予告が SP リーチに乗って来る度合い）。
// ============================================================
const EVA_SP_BOOST = 1000; // 予告の層
const EVA_LEVER_SP_BOOST = 300; // 当該レバブル
const EVA_BIT = 1048576; // 2^20
const EVA_N_HIT = 3280; // 通常/時短 1/319.688
const EVA_S_HIT = 10544; // ST 1/99.448
const EVA_JT_HIGHBASE = 500; // 電サポ中（ST・時短）のヘソ通常当りの時短回数（実機どおり）

// 当り種別：ヘソ当りの振り分け（実機 10R確変 3.0%・3R確変 56%・3R通常 41%）。n は比だけに使う
const EVA_CLASSES_N = [
  { id: "r10", label: "10R確変", n: 98, hit: true, st: true },
  { id: "k3", label: "3R確変", n: 1837, hit: true, st: true },
  { id: "t3", label: "3R通常", n: 1345, hit: true, st: false },
];
// ST（右打ち）の当りはすべて 10R 確変
const EVA_CLASSES_S = [
  { id: "r10", label: "10R確変", n: 1, hit: true, st: true },
];
const EVA_KAKUHEN = ["r10", "k3"];
// 3R確変のうち偶数図柄で揃えて昇格で見せる割合（見た目だけ。確率には関係しない）
const EVA_UPGRADE_RATE = 0.183;

// カウントダウン先読みの 3→2→1（保留に居る間の変動に出す。0 は当該でシンジかカヲル）
const EVA_COUNTDOWN_LEAD = ["３\nミサト", "２\nアスカ", "１\nレイ"];

const EVA_SP_REACHES = [
  "synchro",
  "zero",
  "ni",
  "sho",
  "armisael",
  "sahaquiel",
  "final",
];

// --- 通常/時短：リーチに依存しない層（層の中は排他） ---
const EVA_LAYERS_N = [
  {
    key: "hold",
    spBoost: EVA_SP_BOOST,
    label: "保留",
    states: [
      { id: "red", name: "赤保留", trust: 91.0, share: 7, holdType: "red" },
      {
        id: "green",
        name: "緑保留",
        trust: 1.5,
        share: 1.5,
        holdType: "green",
      },
      { id: "blue", name: "青保留", trust: 0.5, share: 1, holdType: "blue" },
      {
        id: "blink",
        name: "点滅保留",
        trust: 0.2,
        share: 0.5,
        holdType: "blink",
      },
      {
        id: "blink-strong",
        name: "強点滅保留",
        trust: 100,
        share: 0.3,
        holdType: "blink-strong",
      },
      {
        id: "rainbow",
        name: "虹保留",
        trust: 100,
        share: 0.5,
        only: EVA_KAKUHEN,
        holdType: "rainbow",
      },
      {
        id: "alert-purple",
        name: "警報保留(紫)",
        trust: 2.1,
        share: 0.5,
        holdType: "alert-purple",
      },
      {
        id: "alert-red",
        name: "警報保留(赤)",
        trust: 32.0,
        share: 1,
        holdType: "alert-red",
      },
      {
        id: "shogoki",
        name: "初号機保留",
        trust: 78.0,
        share: 1.5,
        holdType: "shogoki",
      },
      // 振動保留は当該レバブルと連動する見た目（レバブル保留と同じ）
      {
        id: "vibe",
        name: "振動保留",
        trust: 77.5,
        share: 1.5,
        holdType: "vibe",
      },
      {
        id: "odd-size",
        name: "違和感保留(サイズが少し大きい)",
        trust: 77.9,
        share: 0.5,
        holdType: "odd",
      },
      {
        id: "odd-shape",
        name: "違和感保留(三角形のデザインが違う)",
        trust: 78.5,
        share: 0.5,
        holdType: "odd",
      },
      {
        id: "odd-cycle",
        name: "違和感保留(点滅の周期が違う)",
        trust: 80.1,
        share: 0.5,
        holdType: "odd",
      },
      {
        id: "lance-red",
        name: "ロンギヌスの槍保留変化(赤)",
        trust: 70.8,
        share: 1,
        holdType: "red",
        text: "ロンギヌスの槍",
      },
      {
        id: "lance-rainbow",
        name: "ロンギヌスの槍保留変化(虹)",
        trust: 100,
        share: 0.2,
        only: EVA_KAKUHEN,
        holdType: "rainbow",
        text: "ロンギヌスの槍",
      },
    ],
  },
  {
    // 保留入賞時の演出（lead: "entry"＝入賞した変動で出す。当該では出さない）
    key: "entry",
    spBoost: EVA_SP_BOOST,
    lead: "entry",
    label: "入賞時",
    states: [
      {
        id: "lamp-white",
        name: "入賞時ランプフラッシュ(白)",
        trust: 7.2,
        share: 0.5,
      },
      {
        id: "lamp-red",
        name: "入賞時ランプフラッシュ(赤)",
        trust: 13.5,
        share: 0.5,
      },
      {
        id: "lamp-rainbow",
        name: "入賞時ランプフラッシュ(虹)",
        trust: 100,
        share: 0.2,
        only: EVA_KAKUHEN,
        fx: "fx-rainbow-frame",
      },
      {
        id: "lamp-awake",
        name: "入賞時ランプフラッシュ(覚醒目)",
        trust: 100,
        share: 0.2,
        text: "覚醒",
        fx: "fx-awake",
      },
      // 実機のレバブル（デバイス振動先読み）。当該レバブル（シミュ専用）とは別
      {
        id: "device-short",
        name: "デバイス振動先読み(ショート)",
        trust: 71.3,
        share: 1.5,
        holdShake: true, // 入賞から消化まで、その保留をレバブルと同じように震わせる
        text: "レバー振動",
      },
      {
        id: "device-long",
        name: "デバイス振動先読み(ロング)",
        trust: 87.6,
        share: 1,
        holdShake: true,
        text: "レバー振動\nロング",
      },
    ],
  },
  {
    // 前兆（先読み）：lead: "pre"＝保留に居る間の変動から出して当該へつなぐ。
    // state.lead は当該より前の変動に順に出す段（カウントダウンの 3→2→1 など）。無ければ text を繰り返す
    key: "precursor",
    spBoost: EVA_SP_BOOST,
    lead: "pre",
    label: "前兆",
    states: [
      {
        id: "countdown",
        name: "カウントダウン(0:シンジ)",
        trust: 75.4,
        share: 3,
        // 3:ミサト→2:アスカ→1:レイ→0:シンジ（カヲルなら確変濃厚）。0 のキャラで分かるように出す
        lead: EVA_COUNTDOWN_LEAD,
        text: "０\nシンジ",
      },
      {
        id: "countdown-kaworu",
        name: "カウントダウン(0:カヲル)",
        trust: 100,
        share: 0.2,
        only: EVA_KAKUHEN,
        lead: EVA_COUNTDOWN_LEAD,
        text: "０\nカヲル",
        color: "rainbow",
      },
      {
        id: "sound-1",
        name: "SOUND ONLY(さあ 行こう)",
        trust: 0.7,
        share: 0.3,
        text: "SOUND ONLY\nさあ 行こう",
      },
      {
        id: "sound-2",
        name: "SOUND ONLY(責任は取ってもらうぞ)",
        trust: 4.1,
        share: 0.3,
        text: "SOUND ONLY\n責任は取ってもらうぞ",
      },
      {
        id: "sound-3",
        name: "SOUND ONLY(三度の報いの時がいま)",
        trust: 72.0,
        share: 1,
        text: "SOUND ONLY\n三度の報いの時がいま",
      },
      {
        id: "sound-4",
        name: "SOUND ONLY(ご苦労だった)",
        trust: 100,
        share: 0.2,
        text: "SOUND ONLY\nご苦労だった",
      },
      {
        id: "sound-5",
        name: "SOUND ONLY(約束の時は近い)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "SOUND ONLY\n約束の時は近い",
      },
      {
        id: "dokkun",
        name: "ドックン前兆",
        trust: 67.4,
        share: 2,
        text: "ドックン…",
        fx: "fx-heartbeat",
      },
      {
        id: "alert-max",
        name: "ALERT前兆(LV.MAX)",
        trust: 4.0,
        share: 0.3,
        lead: ["ALERT\nLV.1", "ALERT\nLV.2"],
        text: "ALERT\nLV.MAX",
      },
      // 暴走入賞は暴走ボーナス（ST 確定の 3R）濃厚
      {
        id: "boso",
        name: "暴走入賞予告",
        trust: 100,
        share: 0.2,
        only: EVA_KAKUHEN,
        text: "暴走",
        fx: "fx-boso",
      },
      {
        id: "moon",
        name: "月背景",
        trust: 63.3,
        share: 1,
        text: "月背景",
        fx: "fx-moon",
      },
    ],
  },
  {
    // 変動開始時の演出
    key: "start",
    spBoost: EVA_SP_BOOST,
    label: "変動開始時",
    states: [
      {
        id: "impact",
        name: "変動開始時インパクト",
        trust: 5.0,
        share: 0.5,
        text: "IMPACT",
      },
      {
        id: "impact-red",
        name: "変動開始時インパクト(強・赤)",
        trust: 76.4,
        share: 1,
        text: "IMPACT",
        fx: "fx-impact-red",
      },
      { id: "logo-white", name: "ロゴランプ(白)", trust: 0.7, share: 0.3 },
      {
        id: "logo-red",
        name: "ロゴランプ(赤)",
        trust: 40.2,
        share: 1,
        fx: "fx-logo-red",
      },
      {
        id: "gimmick",
        name: "役物可動",
        trust: 17.2,
        share: 0.5,
        text: "役物可動",
      },
      { id: "board-in", name: "盤面ランプ(集光)", trust: 5.4, share: 0.3 },
      { id: "board-out", name: "盤面ランプ(散光)", trust: 0.1, share: 0.05 },
      { id: "zoom", name: "図柄拡大", trust: 0.4, share: 0.2 },
      { id: "zoom-red", name: "図柄拡大(赤)", trust: 12.0, share: 0.5 },
    ],
  },
  {
    // 一発告知・確定系
    key: "oneshot",
    label: "一発告知",
    states: [
      {
        id: "fukuin-air",
        name: "福音エアー",
        trust: 100,
        share: 0.5,
        text: "福音エアー",
        fx: "fx-fukuin",
      },
      {
        id: "impact-flash",
        name: "インパクトフラッシュ",
        trust: 100,
        share: 0.5,
        only: EVA_KAKUHEN,
        text: "IMPACT FLASH",
        fx: "fx-impact-flash",
      },
      {
        id: "roar",
        name: "初号機咆哮",
        trust: 100,
        share: 0.3,
        text: "咆哮",
        fx: "fx-roar",
      },
      {
        id: "kaworu-digit",
        name: "カヲル図柄",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "カヲル図柄",
      },
      // 格納庫背景は零号機・弐号機・初号機とも確変濃厚（四号機は 10R確変濃厚なので
      // 全回転リーチの見せ方として eva-engine.js の createEvaJob で付ける）
      {
        id: "hangar-zero",
        name: "格納庫背景(零号機)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "格納庫\n零号機",
      },
      {
        id: "hangar-ni",
        name: "格納庫背景(弐号機)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "格納庫\n弐号機",
      },
      {
        id: "hangar-sho",
        name: "格納庫背景(初号機)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "格納庫\n初号機",
      },
      {
        id: "silent",
        name: "サイレント擬似連(通常変動後)",
        trust: 100,
        share: 0.2,
        only: EVA_KAKUHEN,
        text: "擬似連",
      },
    ],
  },
  {
    // リーチ前予告（ステップアップ・キャラ連続・セリフ）
    key: "pre-step",
    spBoost: EVA_SP_BOOST,
    label: "リーチ前予告",
    states: [
      {
        id: "su-silver5",
        name: "ステップアップ(銀SU5)",
        trust: 8.5,
        share: 0.3,
        text: "STEP UP 5",
      },
      {
        id: "su-silver-jump5",
        name: "ステップアップ(銀ジャンプSU5)",
        trust: 9.6,
        share: 0.2,
        text: "STEP UP 5",
      },
      {
        id: "su-silver-rotate",
        name: "ステップアップ(銀・横回転)",
        trust: 100,
        share: 0.1,
        text: "STEP UP 回転",
      },
      {
        id: "su-gold1",
        name: "ステップアップ(金SU1)",
        trust: 42.0,
        share: 0.3,
        text: "STEP UP 金1",
      },
      {
        id: "su-gold3",
        name: "ステップアップ(金SU3)",
        trust: 29.5,
        share: 0.3,
        text: "STEP UP 金3",
      },
      {
        id: "su-gold4",
        name: "ステップアップ(金SU4)",
        trust: 35.9,
        share: 0.3,
        text: "STEP UP 金4",
      },
      {
        id: "su-gold5",
        name: "ステップアップ(金SU5)",
        trust: 67.0,
        share: 1,
        text: "STEP UP 金5",
      },
      {
        id: "su-gold3-long",
        name: "ステップアップ(金SU3ロング)",
        trust: 55.1,
        share: 0.4,
        text: "STEP UP 金3",
      },
      {
        id: "su-gold4-long",
        name: "ステップアップ(金SU4ロング)",
        trust: 55.1,
        share: 0.4,
        text: "STEP UP 金4",
      },
      {
        id: "su-gold5-long",
        name: "ステップアップ(金SU5ロング)",
        trust: 100,
        share: 0.2,
        text: "STEP UP 金5",
      },
      {
        id: "su-sexy",
        name: "セクシーSU",
        trust: 100,
        share: 0.1,
        text: "セクシー",
      },
      {
        id: "chara-rei1",
        name: "キャラ連続(レイ×1)",
        trust: 25.4,
        share: 0.4,
        text: "レイ",
      },
      {
        id: "chara-rei3",
        name: "キャラ連続(レイ×3)",
        trust: 53.3,
        share: 0.5,
        text: "レイ×3",
      },
      {
        id: "chara-asuka1",
        name: "キャラ連続(アスカ×1)",
        trust: 24.3,
        share: 0.4,
        text: "アスカ",
      },
      {
        id: "chara-asuka3",
        name: "キャラ連続(アスカ×3)",
        trust: 52.9,
        share: 0.5,
        text: "アスカ×3",
      },
      {
        id: "chara-shinji1",
        name: "キャラ連続(シンジ×1)",
        trust: 38.4,
        share: 0.5,
        text: "シンジ",
      },
      {
        id: "chara-shinji3",
        name: "キャラ連続(シンジ×3)",
        trust: 83.1,
        share: 1,
        text: "シンジ×3",
      },
      {
        id: "chara-4",
        name: "キャラ連続(4段階)",
        trust: 100,
        share: 0.2,
        text: "連続×4",
      },
      {
        id: "chara-kaworu",
        name: "キャラ連続(カヲル)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "カヲル",
      },
      {
        id: "serif-chance1",
        name: "セリフ予告(チャンス①)",
        trust: 4.7,
        share: 0.2,
        text: "セリフ予告",
      },
      {
        id: "serif-chance2",
        name: "セリフ予告(チャンス②)",
        trust: 22.5,
        share: 0.4,
        text: "セリフ予告",
      },
      {
        id: "serif-silent",
        name: "セリフ予告(・・・・・・・・)",
        trust: 14.4,
        share: 0.2,
        text: "「・・・・・・・・」",
      },
      {
        id: "serif-premium",
        name: "セリフ予告(プレミアム)",
        trust: 100,
        share: 0.2,
        text: "セリフ予告\nプレミアム",
      },
      {
        id: "serif-mizutama",
        name: "セリフ予告(水玉ボタン)",
        trust: 100,
        share: 0.1,
        text: "水玉ボタン",
      },
      {
        id: "serif-kaworu",
        name: "セリフ予告(カヲル)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "カヲル",
      },
    ],
  },
  {
    // リーチ前予告（ゲンドウ発言・変動中フラッシュ・槍役物・図柄送り・ドデカ図柄）
    key: "pre-misc",
    spBoost: EVA_SP_BOOST,
    label: "リーチ前予告(その他)",
    states: [
      {
        id: "gendo-seele",
        name: "ゲンドウ発言(ゼーレからの贈り物だよ)",
        trust: 74.1,
        share: 0.8,
        text: "ゼーレからの贈り物だよ",
      },
      {
        id: "gendo-scenario",
        name: "ゲンドウ発言(すべてはゼーレのシナリオ通りに)",
        trust: 7.1,
        share: 0.1,
        text: "すべてはゼーレのシナリオ通りに",
      },
      {
        id: "gendo-revive",
        name: "ゲンドウ発言(時計の針は元に戻らない)",
        trust: 27.9,
        share: 0.2,
        text: "時計の針は元に戻らない",
      },
      {
        id: "flash-8",
        name: "変動中フラッシュ(8秒後)",
        trust: 3.8,
        share: 0.1,
        fx: "fx-mono",
      },
      {
        id: "flash-11",
        name: "変動中フラッシュ(11秒後)",
        trust: 29.1,
        share: 0.2,
        fx: "fx-mono",
      },
      {
        id: "flash-8-21",
        name: "変動中フラッシュ(8秒後と21秒後)",
        trust: 50.8,
        share: 0.3,
        fx: "fx-mono",
      },
      {
        id: "flash-8-39",
        name: "変動中フラッシュ(8秒後と39秒後)",
        trust: 67.0,
        share: 0.3,
        fx: "fx-mono",
      },
      {
        id: "lance-gimmick",
        name: "槍役物",
        trust: 33.8,
        share: 0.5,
        text: "ロンギヌスの槍",
      },
      { id: "order-rl", name: "図柄送り(右→左停止)", trust: 17.0, share: 0.3 },
      { id: "order-sync", name: "図柄送り(同時停止)", trust: 42.6, share: 0.4 },
      { id: "slide-5", name: "図柄送り(5コマ滑り)", trust: 26.6, share: 0.3 },
      {
        id: "dodeka",
        name: "ドデカ図柄",
        trust: 29.2,
        share: 0.5,
        text: "ドデカ図柄",
      },
      // 背景変化（1geki）
      {
        id: "bg-evening",
        name: "背景変化(夕方)",
        trust: 8.8,
        share: 0.2,
        text: "夕方背景",
      },
      {
        id: "bg-eva-red",
        name: "背景変化(エヴァ背景・赤)",
        trust: 14.2,
        share: 0.2,
        text: "エヴァ背景(赤)",
      },
      {
        id: "bg-moji-red",
        name: "背景変化(文字背景・赤)",
        trust: 14.2,
        share: 0.2,
        text: "文字背景(赤)",
      },
    ],
  },
  {
    // 実機は「デバイス振動先読み」のショート/ロングだけ。当該変動の白/赤/虹はシミュ専用
    // （信頼度は旧来の 90 / 97.6 / 100%。出るのは当りの約3割で、他の演出とも重なる。
    //   fixed＝全体を縮める対象から外して 3 割を保つ。ユーザー方針 2026-10-03）
    key: "lever",
    spBoost: EVA_LEVER_SP_BOOST,
    label: "当該レバブル",
    states: [
      {
        id: "white",
        name: "白レバブル",
        trust: 90,
        share: 18,
        fixed: true,
        vibeColor: "white",
      },
      {
        id: "red",
        name: "赤レバブル",
        trust: 97.6,
        share: 9,
        fixed: true,
        vibeColor: "red",
      },
      {
        id: "rainbow",
        name: "虹レバブル",
        trust: 100,
        share: 3,
        only: EVA_KAKUHEN,
        vibeColor: "rainbow",
      },
    ],
  },
  {
    // リーチは親の層。10R確変はすべて全回転リーチ（でちゃう！「全回転大当り＝通常時の10R確変当り」）
    key: "reach",
    label: "リーチ",
    isReach: true,
    states: [
      {
        id: "zenkaiten",
        name: "全回転リーチ",
        trust: 100,
        share: 3,
        only: ["r10"],
        text: "全回転リーチ\n祝",
      },
      {
        id: "final",
        name: "最終号機リーチ",
        trust: 70.5,
        share: 24,
        text: "最終号機リーチ",
      },
      {
        id: "sahaquiel",
        name: "vsサハクィエル",
        trust: 65.2,
        share: 14,
        text: "VSサハクィエル",
      },
      {
        id: "armisael",
        name: "vsアルミサエル",
        trust: 56.8,
        share: 16,
        text: "VSアルミサエル",
      },
      {
        id: "sho",
        name: "初号機リーチ",
        trust: 34.8,
        share: 36,
        text: "初号機リーチ",
      },
      {
        id: "zero",
        name: "零号機リーチ",
        trust: 10.2,
        share: 8,
        text: "零号機リーチ",
      },
      {
        id: "ni",
        name: "弐号機リーチ",
        trust: 7.2,
        share: 6,
        text: "弐号機リーチ",
      },
      // シンクロ経由の当りは暴走ボーナス（ST 確定の 3R）
      {
        id: "synchro",
        name: "シンクロリーチ",
        trust: 3.1,
        share: 4,
        forceKakuhen: true,
        text: "シンクロリーチ",
      },
      { id: "normal", name: "ノーマルリーチ", trust: 0.2, share: 8 },
    ],
  },
];

// --- 通常/時短：リーチに紐づく層（SP リーチのときだけ出る） ---
const EVA_LINKED_N = [
  {
    key: "after",
    label: "リーチ後予告",
    reaches: EVA_SP_REACHES,
    states: [
      // レイ背景は 400 回転まで。401 回転からは代わりに群予告（下の minRot: 401）が出る（ユーザー方針 2026-10-03）
      {
        id: "rei-bg",
        name: "レイ背景",
        trust: 85.4,
        share: 4,
        maxRot: 400,
        text: "レイ背景",
      },
      // 旧レイ・アスカ・ユイ・加持・キール・零号機の背景は大当り濃厚（確変までは決まらない）
      {
        id: "premium-bg",
        name: "プレミア背景",
        trust: 100,
        share: 1,
        text: "プレミア背景",
      },
      {
        id: "kaworu-bg",
        name: "カヲル背景",
        trust: 100,
        share: 1,
        only: EVA_KAKUHEN,
        text: "カヲル背景",
      },
      // 群予告は実戦上 400 回転以降のみ
      {
        id: "gun-rei",
        name: "群予告(レイ)",
        trust: 81.8,
        share: 1.5,
        minRot: 401,
        text: "群予告",
      },
      {
        id: "gun-asuka",
        name: "群予告(アスカ)",
        trust: 80.4,
        share: 1.5,
        minRot: 401,
        text: "群予告",
      },
      {
        id: "gun-shinji",
        name: "群予告(シンジ)",
        trust: 87.3,
        share: 1.5,
        minRot: 401,
        text: "群予告",
      },
      {
        id: "gun-kaworu",
        name: "群予告(カヲル)",
        trust: 100,
        share: 0.3,
        only: EVA_KAKUHEN,
        minRot: 401,
        text: "群予告",
      },
      {
        id: "voice-anime",
        name: "リーチボイス(図柄アニメ＋キャラボイス)",
        trust: 100,
        share: 0.2,
        text: "リーチ！",
      },
      // 裏ボタンのボイス（1geki）
      {
        id: "voice-chotto",
        name: "リーチボイス(ちょっち期待して)",
        trust: 54.5,
        share: 0.4,
        text: "ちょっち期待して",
      },
      {
        id: "voice-service",
        name: "リーチボイス(サービスサービス)",
        trust: 100,
        share: 0.1,
        text: "サービス、サービス",
      },
      {
        id: "lance-pass-synchro",
        name: "ロンギヌスの槍通過(シンクロ発展)",
        trust: 22.2,
        share: 0.05,
        reaches: ["synchro"],
        text: "ロンギヌスの槍",
        fx: "fx-lance",
      },
      {
        id: "lance-pass-cg",
        name: "ロンギヌスの槍通過(CG系エヴァリーチ発展)",
        trust: 65.2,
        share: 0.3,
        reaches: ["zero", "ni", "sho"],
        text: "ロンギヌスの槍",
        fx: "fx-lance",
      },
      {
        id: "lance-pass-story",
        name: "ロンギヌスの槍通過(ストーリー発展)",
        trust: 80.0,
        share: 0.3,
        reaches: ["armisael", "sahaquiel"],
        text: "ロンギヌスの槍",
        fx: "fx-lance",
      },
      {
        id: "shito-lamp",
        name: "使徒襲来ランプ(白→赤発光)",
        trust: 39.0,
        share: 0.2,
        text: "使徒襲来",
      },
      {
        id: "mid-char",
        name: "中図柄文字変化(赤発光)",
        trust: 33.9,
        share: 0.15,
        text: "使徒襲来",
      },
      {
        id: "kidou-50",
        name: "起動確率50%",
        trust: 41.6,
        share: 0.15,
        text: "起動確率 50%",
      },
      {
        id: "kidou-60",
        name: "起動確率60%",
        trust: 48.2,
        share: 0.15,
        text: "起動確率 60%",
      },
      {
        id: "kidou-70",
        name: "起動確率70%",
        trust: 58.4,
        share: 0.2,
        text: "起動確率 70%",
      },
      {
        id: "kidou-80",
        name: "起動確率80%",
        trust: 77.9,
        share: 0.2,
        text: "起動確率 80%",
      },
      {
        id: "kidou-90",
        name: "起動確率90%",
        trust: 93.2,
        share: 0.15,
        text: "起動確率 90%",
      },
      {
        id: "kidou-99",
        name: "起動確率99%(金)",
        trust: 100,
        share: 0.05,
        text: "起動確率 99%",
      },
      {
        id: "kidou-77",
        name: "起動確率77%(虹)",
        trust: 100,
        share: 0.05,
        text: "起動確率 77%",
      },
      {
        id: "toka",
        name: "初号機透過",
        trust: 27.8,
        share: 0.1,
        reaches: ["synchro"],
        text: "初号機透過",
      },
    ],
  },
  {
    // 発展契機：発展するリーチに対応した予告。対応しないリーチに発展したら（矛盾）大当り濃厚
    key: "trigger",
    label: "発展契機",
    reaches: EVA_SP_REACHES,
    states: [
      {
        id: "title-rei",
        name: "タイトル予告(レイ、心のむこうに)",
        trust: 1.2,
        share: 0.05,
        reaches: ["zero"],
        text: "レイ、心のむこうに",
      },
      {
        id: "title-asuka",
        name: "タイトル予告(アスカ、来日)",
        trust: 0.7,
        share: 0.03,
        reaches: ["ni"],
        text: "アスカ、来日",
      },
      {
        id: "title-otoko",
        name: "タイトル予告(男の戰い)",
        trust: 19.1,
        share: 0.3,
        reaches: ["sho"],
        text: "男の戰い",
      },
      {
        id: "title-air",
        name: "タイトル予告(Air)",
        trust: 62.4,
        share: 0.6,
        reaches: ["final"],
        text: "Air",
      },
      {
        id: "title-namida",
        name: "タイトル予告(涙)",
        trust: 42.2,
        share: 0.4,
        reaches: ["armisael"],
        text: "涙",
      },
      {
        id: "title-kiseki",
        name: "タイトル予告(奇跡の価値は)",
        trust: 75.0,
        share: 0.5,
        reaches: ["sahaquiel"],
        text: "奇跡の価値は",
      },
      {
        id: "title-synchro",
        name: "タイトル予告(シンクロ)",
        trust: 2.0,
        share: 0.03,
        reaches: ["synchro"],
        text: "シンクロ",
      },
      {
        id: "title-last",
        name: "タイトル予告(最後のシ者)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "最後のシ者",
      },
      {
        id: "title-contra",
        name: "タイトル予告(発展先と矛盾)",
        trust: 100,
        share: 0.1,
        text: "タイトル予告",
      },
      // 朱色の警報から出たタイトルは、タイトルを問わず大当り濃厚（1geki）
      {
        id: "title-vermilion",
        name: "タイトル予告(朱色の警報)",
        trust: 100,
        share: 0.1,
        text: "警報(朱)\nタイトル予告",
      },
      {
        id: "shito-isra",
        name: "使徒予告(イスラフェル)",
        trust: 10.1,
        share: 0.05,
        reaches: ["ni"],
        text: "警報\nイスラフェル",
      },
      {
        id: "shito-reli",
        name: "使徒予告(レリエル)",
        trust: 11.1,
        share: 0.05,
        reaches: ["zero"],
        text: "警報\nレリエル",
      },
      {
        id: "shito-zeru",
        name: "使徒予告(ゼルエル)",
        trust: 38.9,
        share: 0.3,
        reaches: ["sho"],
        text: "警報\nゼルエル",
      },
      {
        id: "shito-armi",
        name: "使徒予告(アルミサエル)",
        trust: 87.5,
        share: 0.5,
        reaches: ["armisael"],
        text: "警報\nアルミサエル",
      },
      {
        id: "shito-saha",
        name: "使徒予告(サハクィエル)",
        trust: 90.0,
        share: 0.5,
        reaches: ["sahaquiel"],
        text: "警報\nサハクィエル",
      },
      {
        id: "shito-mass",
        name: "使徒予告(エヴァンゲリオン量産機)",
        trust: 94.2,
        share: 0.5,
        reaches: ["final"],
        text: "警報\n量産機",
      },
      {
        id: "shito-kaworu",
        name: "使徒予告(カヲル)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "警報\nカヲル",
      },
      {
        id: "shito-sakiel",
        name: "使徒予告(リーチの無い使徒)",
        trust: 100,
        share: 0.1,
        text: "警報\nサキエル",
      },
      {
        id: "scene-asuka-kiai",
        name: "名シーン予告(アスカが気合を入れる)",
        trust: 0.7,
        share: 0.02,
        reaches: ["ni"],
        text: "名シーン",
      },
      {
        id: "scene-asuka-rei",
        name: "名シーン予告(アスカとレイが言い合い)",
        trust: 1.1,
        share: 0.03,
        reaches: ["zero"],
        text: "名シーン",
      },
      {
        id: "scene-noru",
        name: "名シーン予告(初号機に乗せてください)",
        trust: 11.3,
        share: 0.15,
        reaches: ["sho"],
        text: "名シーン",
      },
      {
        id: "scene-kettei",
        name: "名シーン予告(ミサトが作戦を決定する)",
        trust: 44.5,
        share: 0.3,
        reaches: ["armisael"],
        text: "名シーン",
      },
      {
        id: "scene-setsumei",
        name: "名シーン予告(ミサトが作戦内容を説明する)",
        trust: 55.7,
        share: 0.3,
        reaches: ["sahaquiel"],
        text: "名シーン",
      },
      {
        id: "scene-mass",
        name: "名シーン予告(量産機が登場する)",
        trust: 71.1,
        share: 0.4,
        reaches: ["final"],
        text: "名シーン",
      },
      // シャッター経由で文字が金（1geki）。突如発生の金は大当り濃厚（下の scene-gold）
      {
        id: "scene-gold-noru",
        name: "名シーン予告(金・初号機に乗せてください)",
        trust: 71.3,
        share: 0.2,
        reaches: ["sho"],
        text: "名シーン(金)",
      },
      {
        id: "scene-gold-kiai",
        name: "名シーン予告(金・アスカが気合を入れる)",
        trust: 37.0,
        share: 0.1,
        reaches: ["ni"],
        text: "名シーン(金)",
      },
      {
        id: "scene-gold-iiai",
        name: "名シーン予告(金・アスカとレイが言い合い)",
        trust: 43.1,
        share: 0.1,
        reaches: ["zero"],
        text: "名シーン(金)",
      },
      {
        id: "scene-gold-kettei",
        name: "名シーン予告(金・ミサトが作戦を決定する)",
        trust: 72.5,
        share: 0.2,
        reaches: ["armisael"],
        text: "名シーン(金)",
      },
      {
        id: "scene-gold-setsumei",
        name: "名シーン予告(金・ミサトが作戦内容を説明する)",
        trust: 80.6,
        share: 0.2,
        reaches: ["sahaquiel"],
        text: "名シーン(金)",
      },
      {
        id: "scene-gold-mass",
        name: "名シーン予告(金・量産機が登場する)",
        trust: 82.6,
        share: 0.2,
        reaches: ["final"],
        text: "名シーン(金)",
      },
      {
        id: "scene-gold",
        name: "名シーン予告(金)",
        trust: 100,
        share: 0.1,
        text: "名シーン(金)",
      },
      {
        id: "next-rei",
        name: "次回予告(レイ、心のむこうに)",
        trust: 56.6,
        share: 0.3,
        reaches: ["zero"],
        text: "次回予告\nレイ、心のむこうに",
      },
      {
        id: "next-asuka",
        name: "次回予告(アスカ、来日)",
        trust: 55.6,
        share: 0.3,
        reaches: ["ni"],
        text: "次回予告\nアスカ、来日",
      },
      {
        id: "next-otoko",
        name: "次回予告(男の戰い)",
        trust: 60.3,
        share: 0.4,
        reaches: ["sho"],
        text: "次回予告\n男の戰い",
      },
      {
        id: "next-namida",
        name: "次回予告(涙)",
        trust: 57.6,
        share: 0.3,
        reaches: ["armisael"],
        text: "次回予告\n涙",
      },
      {
        id: "next-kiseki",
        name: "次回予告(奇跡の価値は)",
        trust: 65.6,
        share: 0.3,
        reaches: ["sahaquiel"],
        text: "次回予告\n奇跡の価値は",
      },
      {
        id: "next-air",
        name: "次回予告(Air)",
        trust: 66.9,
        share: 0.4,
        reaches: ["final"],
        text: "次回予告\nAir",
      },
      {
        id: "next-service",
        name: "次回予告(サービス、サービス)",
        trust: 100,
        share: 0.1,
        text: "次回予告\nサービス、サービス",
      },
      {
        id: "next-kuroji",
        name: "次回予告(黒字に白文字)",
        trust: 100,
        share: 0.1,
        text: "次回予告",
      },
      {
        id: "lamp-zero",
        name: "暗転タイトルランプ(零号機・赤)",
        trust: 9.5,
        share: 0.05,
        reaches: ["zero"],
        text: "タイトルランプ",
      },
      {
        id: "lamp-ni",
        name: "暗転タイトルランプ(弐号機・赤)",
        trust: 26.5,
        share: 0.1,
        reaches: ["ni"],
        text: "タイトルランプ",
      },
      {
        id: "lamp-sho",
        name: "暗転タイトルランプ(初号機・赤)",
        trust: 28.1,
        share: 0.2,
        reaches: ["sho"],
        text: "タイトルランプ",
      },
      {
        id: "lamp-armi",
        name: "暗転タイトルランプ(涙・赤)",
        trust: 60.0,
        share: 0.3,
        reaches: ["armisael"],
        text: "タイトルランプ",
      },
      {
        id: "lamp-saha",
        name: "暗転タイトルランプ(奇跡の価値は・赤)",
        trust: 70.3,
        share: 0.3,
        reaches: ["sahaquiel"],
        text: "タイトルランプ",
      },
      {
        id: "lamp-final",
        name: "暗転タイトルランプ(Air・赤)",
        trust: 77.4,
        share: 0.3,
        reaches: ["final"],
        text: "タイトルランプ",
      },
      // 金シャッター経由（1geki）：レイ・アスカ・男の戰いは発展で大当り濃厚、
      // 涙・奇跡の価値は・Air は回転白→決定赤の値
      {
        id: "lamp-gold-zero",
        name: "暗転タイトルランプ(金シャッター・レイ、心のむこうに)",
        trust: 100,
        share: 0.05,
        reaches: ["zero"],
        text: "タイトルランプ\n金シャッター",
      },
      {
        id: "lamp-gold-ni",
        name: "暗転タイトルランプ(金シャッター・アスカ、来日)",
        trust: 100,
        share: 0.05,
        reaches: ["ni"],
        text: "タイトルランプ\n金シャッター",
      },
      {
        id: "lamp-gold-sho",
        name: "暗転タイトルランプ(金シャッター・男の戰い)",
        trust: 100,
        share: 0.05,
        reaches: ["sho"],
        text: "タイトルランプ\n金シャッター",
      },
      {
        id: "lamp-gold-armi",
        name: "暗転タイトルランプ(金シャッター・涙)",
        trust: 66.9,
        share: 0.2,
        reaches: ["armisael"],
        text: "タイトルランプ\n金シャッター",
      },
      {
        id: "lamp-gold-saha",
        name: "暗転タイトルランプ(金シャッター・奇跡の価値は)",
        trust: 76.1,
        share: 0.2,
        reaches: ["sahaquiel"],
        text: "タイトルランプ\n金シャッター",
      },
      {
        id: "lamp-gold-final",
        name: "暗転タイトルランプ(金シャッター・Air)",
        trust: 82.2,
        share: 0.2,
        reaches: ["final"],
        text: "タイトルランプ\n金シャッター",
      },
      {
        id: "lamp-last",
        name: "暗転タイトルランプ(最後のシ者)",
        trust: 100,
        share: 0.05,
        text: "タイトルランプ\n最後のシ者",
      },
      {
        id: "lamp-rainbow",
        name: "暗転タイトルランプ(虹)",
        trust: 100,
        share: 0.1,
        only: EVA_KAKUHEN,
        text: "タイトルランプ\n虹",
      },
      {
        id: "meeting-silver",
        name: "作戦会議(銀シャッター)",
        trust: 1.4,
        share: 0.02,
        reaches: ["zero", "ni", "sho"],
        text: "作戦会議",
      },
      {
        id: "meeting-gold",
        name: "作戦会議(金シャッター)",
        trust: 42.7,
        share: 0.2,
        reaches: ["zero", "ni", "sho"],
        text: "作戦会議\n金シャッター",
      },
      {
        id: "meeting-urgent",
        name: "緊急作戦会議(金シャッター)",
        trust: 32.7,
        share: 0.1,
        reaches: ["zero", "ni", "sho"],
        text: "緊急作戦会議",
      },
      {
        id: "barake-white",
        name: "バラケ目発進(セリフ白)",
        trust: 6.7,
        share: 0.05,
        text: "発進",
      },
      {
        id: "barake-red",
        name: "バラケ目発進(セリフ赤)",
        trust: 33.9,
        share: 0.2,
        text: "発進",
      },
    ],
  },
  {
    // SP 発展演出（SP リーチに付く部品：信頼度の最大には使うが「2 つ以上」には数えない）
    key: "launch",
    label: "SP発展演出",
    component: true,
    reaches: ["zero", "ni", "sho", "armisael", "sahaquiel", "final"],
    states: [
      { id: "three", name: "SP発展(3機発進)", trust: 5.7, rate: 0.7 },
      {
        id: "solo-zero",
        name: "SP発展(零号機単機)",
        trust: 40.2,
        rate: 0.15,
        reaches: ["zero"],
        text: "零号機 単機発進",
      },
      {
        id: "solo-ni",
        name: "SP発展(弐号機単機)",
        trust: 43.6,
        rate: 0.15,
        reaches: ["ni"],
        text: "弐号機 単機発進",
      },
      {
        id: "solo-sho",
        name: "SP発展(初号機単機)",
        trust: 74.3,
        rate: 0.1,
        reaches: ["sho"],
        text: "初号機 単機発進",
      },
      {
        id: "red-bg",
        name: "SP発展(赤背景)",
        trust: 53.4,
        rate: 0.04,
        text: "発進",
      },
      {
        id: "mirai",
        name: "SP発展(あなた達に未来を託すわ)",
        trust: 100,
        rate: 0.005,
        text: "あなた達に未来を託すわ",
      },
    ],
  },
  {
    // リーチ中のチャンスアップ（リーチの部品：数えない）
    key: "chanceup",
    label: "リーチ中のチャンスアップ",
    component: true,
    reaches: EVA_SP_REACHES,
    states: [
      {
        id: "cutin-gold-zero",
        name: "最終カットイン(金)",
        trust: 64.3,
        rate: 0.04,
        reaches: ["zero"],
        text: "カットイン 金",
      },
      {
        id: "cutin-gold-ni",
        name: "最終カットイン(金)",
        trust: 62.6,
        rate: 0.04,
        reaches: ["ni"],
        text: "カットイン 金",
      },
      {
        id: "cutin-gold-sho",
        name: "最終カットイン(金)",
        trust: 63.9,
        rate: 0.08,
        reaches: ["sho"],
        text: "カットイン 金",
      },
      // モニターカットインの 4 種類目のセリフは機体ごとに大当り濃厚（1geki）
      {
        id: "cutin-monitor-zero",
        name: "モニターカットイン(必ず仕留めるわ)",
        trust: 100,
        rate: 0.01,
        reaches: ["zero"],
        text: "必ず仕留めるわ",
      },
      {
        id: "cutin-monitor-ni",
        name: "モニターカットイン(引導を渡してあげるわ)",
        trust: 100,
        rate: 0.01,
        reaches: ["ni"],
        text: "引導を渡してあげるわ",
      },
      {
        id: "cutin-intro-gold",
        name: "モニターカットイン(必ず殲滅する)",
        trust: 100,
        rate: 0.01,
        reaches: ["sho"],
        text: "必ず殲滅する",
      },
      {
        id: "telop-zero",
        name: "赤テロップ(後半)",
        trust: 34.6,
        rate: 0.05,
        reaches: ["zero"],
        text: "赤テロップ",
      },
      {
        id: "telop-ni",
        name: "赤テロップ(後半)",
        trust: 19.0,
        rate: 0.05,
        reaches: ["ni"],
        text: "赤テロップ",
      },
      {
        id: "telop-sho",
        name: "赤テロップ(後半)",
        trust: 57.9,
        rate: 0.08,
        reaches: ["sho"],
        text: "赤テロップ",
      },
      {
        id: "weapon-kaji",
        name: "特殊武器ルート(加持)",
        trust: 81.5,
        rate: 0.02,
        reaches: ["zero", "ni", "sho"],
        text: "特殊武器",
      },
      {
        id: "eye-flash",
        name: "裏ボタン 初号機眼光発光",
        trust: 100,
        rate: 0.005,
        reaches: ["zero", "ni", "sho"],
        text: "眼光",
      },
      {
        id: "telop-story",
        name: "赤テロップ",
        trust: 75.5,
        rate: 0.2,
        reaches: ["armisael"],
        text: "赤テロップ",
      },
      {
        id: "telop-saha",
        name: "赤テロップ",
        trust: 81.5,
        rate: 0.2,
        reaches: ["sahaquiel"],
        text: "赤テロップ",
      },
      {
        id: "toka-weak3-armi",
        name: "初号機透過(弱発光×3)",
        trust: 84.2,
        rate: 0.08,
        reaches: ["armisael"],
        text: "初号機透過",
      },
      {
        id: "toka-weak3-saha",
        name: "初号機透過(弱発光×3)",
        trust: 89.4,
        rate: 0.08,
        reaches: ["sahaquiel"],
        text: "初号機透過",
      },
      {
        id: "toka-strong",
        name: "初号機透過(強発光)",
        trust: 100,
        rate: 0.03,
        reaches: ["armisael", "sahaquiel"],
        text: "初号機透過\n強発光",
      },
      {
        id: "lever-story",
        name: "レバー振動",
        trust: 100,
        rate: 0.01,
        reaches: ["armisael", "sahaquiel"],
        text: "レバー振動",
      },
      {
        id: "gabure-silver",
        name: "画ブレ(銀)",
        trust: 63.1,
        rate: 0.25,
        reaches: ["final"],
        text: "画ブレ 銀",
      },
      {
        id: "gabure-gold",
        name: "画ブレ(金)",
        trust: 89.5,
        rate: 0.15,
        reaches: ["final"],
        text: "画ブレ 金",
      },
      {
        id: "emergency",
        name: "EMERGENCY(強)",
        trust: 30.1,
        rate: 0.05,
        reaches: ["synchro"],
        text: "EMERGENCY",
      },
      {
        id: "synchro-red",
        name: "シンクロメーター(シンジ・大)",
        trust: 40.2,
        rate: 0.03,
        reaches: ["synchro"],
        text: "シンクロ率 MAX",
      },
      {
        id: "synchro-rei-small",
        name: "シンクロメーター(レイ・小)",
        trust: 100,
        rate: 0.005,
        reaches: ["synchro"],
        text: "シンクロ率",
      },
    ],
  },
];

// ============================================================
// ST「IMPACT MODE」シンジモード（違和感保留の 3 種はでちゃう！の同じ表の値）
// ST 中の当りはすべて 10R 確変なので、濃厚の演出はすべて「当り濃厚」になる。
// ============================================================
const EVA_ST_SOKU_SP = ["sakiel", "zeruel"];
const EVA_ST_EVA_SP = ["st-sho", "st-ni", "st-zero"];
const EVA_ST_SP = [...EVA_ST_SOKU_SP, ...EVA_ST_EVA_SP, "dummy", "mission"];

const EVA_LAYERS_S = [
  {
    key: "hold",
    spBoost: EVA_SP_BOOST,
    label: "保留",
    states: [
      { id: "red", name: "赤保留", trust: 95.1, share: 4, holdType: "red" },
      {
        id: "green",
        name: "緑保留",
        trust: 41.9,
        share: 1.5,
        holdType: "green",
      },
      { id: "blue", name: "青保留", trust: 20.8, share: 1, holdType: "blue" },
      {
        id: "rainbow",
        name: "虹保留",
        trust: 100,
        share: 0.5,
        holdType: "rainbow",
      },
      {
        id: "odd-reverse",
        name: "違和感保留(文字が逆に流れる)",
        trust: 69.8,
        share: 1,
        // ST の箱は中の文字が流れるので、違和感は 3 種を見た目で分ける（style.css の heso-odd-*）
        holdType: "odd-reverse",
      },
      {
        id: "odd-noise",
        name: "違和感保留(全体にノイズ)",
        trust: 28.0,
        share: 0.3,
        holdType: "odd-noise",
      },
      {
        id: "odd-blank",
        name: "違和感保留(中の文字なし)",
        trust: 13.9,
        share: 0.2,
        holdType: "odd-blank",
      },
      {
        id: "caution",
        name: "CAUTION/EMERGENCY保留",
        trust: 0.9,
        share: 0.05,
        holdType: "caution",
      },
      // 当該変動のシフト変化（なな徹 ST中の保留変化）。保留にいる間は無地で、
      // 消化を始めた当該保留だけ色が変わる（shift: true）
      {
        id: "shift-blue",
        name: "シフト変化(青)",
        trust: 29.4,
        share: 0.5,
        holdType: "blue",
        shift: true,
        text: "シフト変化",
      },
      {
        id: "shift-green",
        name: "シフト変化(緑)",
        trust: 45.7,
        share: 0.7,
        holdType: "green",
        shift: true,
        text: "シフト変化",
      },
      {
        id: "shift-red",
        name: "シフト変化(赤)",
        trust: 95.7,
        share: 2,
        holdType: "red",
        shift: true,
        text: "シフト変化",
      },
      {
        id: "shift-rainbow",
        name: "シフト変化(虹)",
        trust: 100,
        share: 0.3,
        holdType: "rainbow",
        shift: true,
        text: "シフト変化",
      },
    ],
  },
  {
    // レバブル先読みは入賞した変動で震える（当該では出さない）
    key: "lever-pre",
    spBoost: EVA_SP_BOOST,
    lead: "entry",
    label: "レバブル先読み",
    states: [
      {
        id: "short",
        name: "レバブル先読み(ショート)",
        trust: 95.6,
        share: 1.5,
        holdShake: true,
        text: "レバブル先読み",
      },
      {
        id: "long",
        name: "レバブル先読み(ロング)",
        trust: 100,
        share: 0.5,
        holdShake: true,
        text: "レバブル先読み\nロング",
      },
    ],
  },
  {
    // 前兆（先読み）：保留に居る間の変動から出して当該へつなぐ（通常時の precursor と同じ）
    key: "precursor",
    spBoost: EVA_SP_BOOST,
    lead: "pre",
    label: "前兆",
    states: [
      {
        id: "countdown",
        name: "カウントダウン",
        trust: 85.2,
        share: 2,
        lead: EVA_COUNTDOWN_LEAD,
        text: "０\nシンジ",
      },
      {
        id: "countdown-kaworu",
        name: "カウントダウン(0:カヲル)",
        trust: 100,
        share: 0.3,
        lead: EVA_COUNTDOWN_LEAD,
        text: "０\nカヲル",
        color: "rainbow",
      },
      {
        id: "eyecatch-red",
        name: "アイキャッチ(赤)",
        trust: 69.5,
        share: 1.5,
        text: "アイキャッチ",
      },
      {
        id: "eyecatch-white",
        name: "アイキャッチ(白×4)",
        trust: 29.5,
        share: 0.3,
        text: "アイキャッチ",
      },
      {
        id: "dokkun",
        name: "ドックン",
        trust: 66.4,
        share: 1,
        text: "ドックン",
      },
      {
        id: "dokkun-red",
        name: "ドックン(赤)",
        trust: 84.8,
        share: 1,
        text: "ドックン",
      },
      {
        id: "sakiel-pre",
        name: "使徒襲来(サキエル)",
        trust: 73.1,
        share: 1,
        text: "使徒襲来",
      },
      {
        id: "zeruel-pre",
        name: "使徒襲来(ゼルエル)",
        trust: 17.3,
        share: 0.3,
        text: "使徒襲来",
      },
      {
        id: "accel",
        name: "初号機加速",
        trust: 31.9,
        share: 0.5,
        text: "初号機加速",
      },
      {
        id: "mission-pre",
        name: "ミッションモード前兆",
        trust: 45.2,
        share: 1,
        text: "CAUTION",
      },
      {
        id: "search-pre",
        name: "敵探索前兆",
        trust: 13.1,
        share: 0.3,
        text: "警報",
      },
    ],
  },
  {
    key: "screen",
    spBoost: EVA_SP_BOOST,
    lead: "pre",
    label: "画面系の前兆",
    states: [
      {
        id: "logo-green",
        name: "ロゴフラッシュ(緑ロング)",
        trust: 79.1,
        share: 1,
      },
      {
        id: "logo-red",
        name: "ロゴフラッシュ(赤ロング)",
        trust: 91.2,
        share: 1,
      },
      {
        id: "logo-rainbow",
        name: "ロゴフラッシュ(虹)",
        trust: 100,
        share: 0.2,
      },
      { id: "stop-green", name: "図柄停止時発光(緑)", trust: 45.2, share: 0.7 },
      { id: "stop-red", name: "図柄停止時発光(赤)", trust: 60.1, share: 0.7 },
      {
        id: "stop-rainbow",
        name: "図柄停止時発光(虹)",
        trust: 100,
        share: 0.2,
      },
      { id: "mute-white", name: "変動音オフ(白)", trust: 81.7, share: 1 },
      { id: "mute-red", name: "変動音オフ(赤)", trust: 90.7, share: 0.7 },
      {
        id: "remain-red",
        name: "残り回数表示(赤文字)",
        trust: 86.8,
        share: 0.7,
      },
      {
        id: "remain-noise",
        name: "残り回数表示(ノイズ大)",
        trust: 90.3,
        share: 0.4,
      },
      {
        id: "remain-noise-small",
        name: "残り回数表示(ノイズ小)",
        trust: 53.0,
        share: 0.4,
      },
      {
        id: "remain-shake",
        name: "残り回数表示(ガタガタ)",
        trust: 52.3,
        share: 0.4,
      },
      {
        id: "remain-rainbow",
        name: "残り回数表示(虹文字)",
        trust: 100,
        share: 0.1,
      },
      {
        id: "chance-bg",
        name: "チャンス背景変化",
        trust: 86.3,
        share: 1.5,
        text: "チャンス背景",
      },
      { id: "bg-noise", name: "背景ノイズ違和感(大)", trust: 80.0, share: 0.7 },
    ],
  },
  {
    key: "midway",
    spBoost: EVA_SP_BOOST,
    label: "変動中予告",
    states: [
      {
        id: "su-white3",
        name: "ステップアップ(白SU3)",
        trust: 15.6,
        share: 0.5,
        text: "STEP UP",
      },
      {
        id: "su-white4",
        name: "ステップアップ(白SU4)",
        trust: 40.8,
        share: 0.7,
        text: "STEP UP 4",
      },
      {
        id: "su-red3",
        name: "ステップアップ(赤SU3)",
        trust: 62.1,
        share: 1,
        text: "STEP UP 赤",
      },
      {
        id: "su-gold3",
        name: "ステップアップ(金SU3)",
        trust: 93.3,
        share: 0.7,
        text: "STEP UP 金",
      },
      {
        id: "su-kaworu",
        name: "ステップアップ(カヲル)",
        trust: 100,
        share: 0.1,
        text: "STEP UP カヲル",
      },
      {
        id: "chance-green",
        name: "エヴァチャンス文字(CHANCE緑)",
        trust: 74.3,
        share: 1,
        text: "CHANCE",
      },
      {
        id: "chance-red",
        name: "エヴァチャンス文字(CHANCE赤)",
        trust: 63.4,
        share: 0.7,
        text: "CHANCE",
      },
      // 1geki のエヴァチャンス文字予告：白は SU2 止まりのほうが濃厚、ノイズ付きは格上げ
      {
        id: "chance-white-su2",
        name: "エヴァチャンス文字(白SU2)",
        trust: 100,
        share: 0.1,
        text: "CHANCE",
        color: "white",
      },
      {
        id: "chance-red-noise",
        name: "エヴァチャンス文字(赤SU3・ノイズ)",
        trust: 80.8,
        share: 0.4,
        text: "CHANCE",
      },
      {
        id: "chance-gold-noise",
        name: "エヴァチャンス文字(金SU3・ノイズ)",
        trust: 100,
        share: 0.1,
        text: "CHANCE",
      },
      {
        id: "chance-other",
        name: "エヴァチャンス文字(CHANCE以外)",
        trust: 100,
        share: 0.2,
        text: "REACH",
      },
      {
        id: "shito-armisael",
        name: "新使徒予告(アルミサエル)",
        trust: 72.9,
        share: 0.7,
        text: "アルミサエル",
      },
      {
        id: "shito-shamshel",
        name: "新使徒予告(シャムシエル)",
        trust: 82.7,
        share: 0.7,
        text: "シャムシエル",
      },
      {
        id: "shito-kaworu",
        name: "新使徒予告(渚カヲル)",
        trust: 100,
        share: 0.1,
        text: "渚カヲル",
      },
      {
        id: "cut-white",
        name: "高速キャラカットSU(白SU4)",
        trust: 40.4,
        share: 0.7,
      },
      {
        id: "cut-red",
        name: "高速キャラカットSU(赤SU4)",
        trust: 74.3,
        share: 0.7,
      },
      {
        id: "cut-gold",
        name: "高速キャラカットSU(金SU4)",
        trust: 88.3,
        share: 0.5,
      },
      { id: "serif-2", name: "セリフ予告(2段階)", trust: 13.7, share: 0.5 },
      {
        id: "serif-3",
        name: "セリフ予告(3段階)",
        trust: 80.0,
        share: 1,
        text: "セリフ予告",
      },
      {
        id: "serif-premium",
        name: "セリフ予告(プレミア)",
        trust: 100,
        share: 0.2,
        text: "パーペキね",
      },
      {
        id: "search-isra-white",
        name: "敵探索(イスラフェル白文字)",
        trust: 46.9,
        share: 0.4,
        text: "イスラフェル",
      },
      {
        id: "search-isra-red",
        name: "敵探索(イスラフェル赤文字)",
        trust: 65.0,
        share: 0.4,
        text: "イスラフェル",
      },
      {
        id: "search-sham-white",
        name: "敵探索(シャムシエル白文字)",
        trust: 66.7,
        share: 0.4,
        text: "シャムシエル",
      },
      {
        id: "search-sham-red",
        name: "敵探索(シャムシエル赤文字)",
        trust: 78.9,
        share: 0.4,
        text: "シャムシエル",
      },
      {
        id: "panel-right",
        name: "パネル予告(右選択・左金)",
        trust: 93.6,
        share: 0.4,
        text: "パネル予告",
      },
      {
        id: "panel-left",
        name: "パネル予告(左選択・左赤右金)",
        trust: 62.2,
        share: 0.4,
        text: "パネル予告",
      },
      {
        id: "panel-kaji",
        name: "パネル予告(加持・金)",
        trust: 93.8,
        share: 0.2,
        text: "パネル予告",
      },
      // キャラ別（1geki）
      {
        id: "panel-kaji-normal",
        name: "パネル予告(加持)",
        trust: 89.3,
        share: 0.3,
        text: "パネル予告\n加持",
      },
      {
        id: "panel-rei-red",
        name: "パネル予告(レイ・赤)",
        trust: 100,
        share: 0.1,
        text: "パネル予告\nレイ",
      },
      {
        id: "panel-kaworu-gold",
        name: "パネル予告(カヲル・金)",
        trust: 100,
        share: 0.1,
        text: "パネル予告\nカヲル",
      },
      {
        id: "push-kaworu",
        name: "押しボタン(カヲルシート発光)",
        trust: 100,
        share: 0.1,
        text: "PUSH",
        color: "rainbow",
      },
      {
        id: "push-red",
        name: "押しボタン(押せ文字赤)",
        trust: 72.1,
        share: 0.7,
        text: "PUSH",
      },
      { id: "push", name: "押しボタン", trust: 40.9, share: 0.7, text: "PUSH" },
      {
        id: "next-preview",
        name: "新次回予告",
        trust: 100,
        share: 0.2,
        text: "次回予告\nサービス、サービス",
      },
    ],
  },
  {
    key: "flash",
    spBoost: EVA_SP_BOOST,
    label: "一発告知・枠フラッシュ",
    states: [
      {
        id: "impact-flash",
        name: "インパクトフラッシュ",
        trust: 100,
        share: 1,
        text: "IMPACT",
        fx: "fx-impact-flash",
      },
      {
        id: "fukuin-air",
        name: "福音エアー",
        trust: 100,
        share: 0.5,
        text: "福音エアー",
        fx: "fx-fukuin",
      },
      { id: "kaworu-button", name: "カヲルボタン", trust: 100, share: 0.2 },
      { id: "frame-eye", name: "枠初号機眼光", trust: 100, share: 0.2 },
      { id: "frame-weak", name: "枠フラッシュ(弱・白)", trust: 48.4, share: 1 },
      {
        id: "frame-strong",
        name: "枠フラッシュ(強・赤)",
        trust: 91.6,
        share: 1,
      },
      { id: "frame-late", name: "枠フラッシュ(遅れ)", trust: 100, share: 0.2 },
    ],
  },
  {
    // シミュ専用の当該レバブル。ST 中はどれも当り確定、出るのは当りの約2割
    // （ユーザー方針 2026-10-03）。白:赤:虹 の比は旧来（6720:2880:800）のまま
    key: "lever",
    spBoost: EVA_LEVER_SP_BOOST,
    label: "当該レバブル",
    states: [
      {
        id: "white",
        name: "白レバブル",
        trust: 100,
        share: 12.93,
        vibeColor: "white",
      },
      {
        id: "red",
        name: "赤レバブル",
        trust: 100,
        share: 5.54,
        vibeColor: "red",
      },
      {
        id: "rainbow",
        name: "虹レバブル",
        trust: 100,
        share: 1.53,
        vibeColor: "rainbow",
      },
    ],
  },
  {
    key: "reach",
    label: "リーチ",
    isReach: true,
    states: [
      {
        id: "sakiel",
        name: "即SP vsサキエル",
        trust: 84.9,
        share: 12,
        text: "VSサキエル",
      },
      {
        id: "zeruel",
        name: "即SP vsゼルエル",
        trust: 26.8,
        share: 4,
        text: "VSゼルエル",
      },
      {
        id: "st-sho",
        name: "初号機vsシャムシエル",
        trust: 71.5,
        share: 8,
        text: "初号機VSシャムシエル",
      },
      {
        id: "st-ni",
        name: "弐号機vs量産型",
        trust: 60.2,
        share: 5,
        text: "弐号機VS量産型",
      },
      {
        id: "st-zero",
        name: "零号機vsイスラフェル",
        trust: 55.8,
        share: 3,
        text: "零号機VSイスラフェル",
      },
      {
        id: "dummy",
        name: "ダミー初号機リーチ",
        trust: 80.5,
        share: 8,
        text: "ダミー初号機リーチ",
      },
      {
        id: "mission",
        name: "ミッションモード",
        trust: 42.5,
        share: 3,
        text: "ミッションモード",
      },
      {
        id: "zenkaiten",
        name: "全回転リーチ",
        trust: 100,
        share: 2,
        text: "全回転リーチ\n祝",
      },
      // SP に発展しないテンパイ（図柄煽り）
      { id: "tenpai", name: "図柄テンパイ", trust: 5, share: 3 },
    ],
  },
];

// ST：SP リーチに必ず付く部品の層（信頼度の最大には使うが「2 つ以上」には数えない）。
// rate はそのリーチのときに出る割合の推定値
const EVA_LINKED_S = [
  {
    // SP に発展しないテンパイの煽り（1geki）。チャンスアップが付くと一気に上がる
    key: "aori",
    label: "テンパイ煽り",
    component: true,
    reaches: ["tenpai"],
    states: [
      {
        id: "aori-zugara",
        name: "テンパイ煽り(図柄煽り)",
        trust: 13.5,
        rate: 0.3,
        text: "図柄煽り",
      },
      {
        id: "aori-zugara-cu",
        name: "テンパイ煽り(図柄煽り・チャンスアップ)",
        trust: 77.1,
        rate: 0.03,
        text: "図柄煽り\nCHANCE UP",
        color: "red",
      },
      {
        id: "aori-synchro",
        name: "テンパイ煽り(シンクロメーター)",
        trust: 18.0,
        rate: 0.25,
        text: "シンクロメーター",
      },
      {
        id: "aori-synchro-cu",
        name: "テンパイ煽り(シンクロメーター・チャンスアップ)",
        trust: 74.2,
        rate: 0.03,
        text: "シンクロメーター\nCHANCE UP",
        color: "red",
      },
      {
        id: "aori-dummy",
        name: "テンパイ煽り(ダミープラグ)",
        trust: 18.5,
        rate: 0.2,
        text: "ダミープラグ",
      },
      {
        id: "aori-dummy-cu",
        name: "テンパイ煽り(ダミープラグ・チャンスアップ)",
        trust: 89.1,
        rate: 0.02,
        text: "ダミープラグ\nCHANCE UP",
        color: "red",
      },
    ],
  },
  {
    // 即 SP リーチの期待度表示（1geki）
    key: "expect",
    label: "期待度表示",
    component: true,
    reaches: EVA_ST_SOKU_SP,
    states: [
      {
        id: "expect-80-sakiel",
        name: "期待度表示(サキエル80%)",
        trust: 91.4,
        reaches: ["sakiel"],
        rate: 0.2,
        text: "期待度 80%",
        color: "red",
      },
      {
        id: "expect-80-zeruel",
        name: "期待度表示(ゼルエル80%)",
        trust: 90.3,
        reaches: ["zeruel"],
        rate: 0.05,
        text: "期待度 80%",
        color: "red",
      },
      {
        id: "expect-77",
        name: "期待度表示(77%)",
        trust: 100,
        rate: 0.01,
        text: "期待度 77%",
        color: "rainbow",
      },
      {
        id: "expect-99",
        name: "期待度表示(99%)",
        trust: 100,
        rate: 0.01,
        text: "期待度 99%",
        color: "gold",
      },
    ],
  },
  {
    key: "device",
    label: "入力デバイス",
    component: true,
    reaches: [...EVA_ST_SOKU_SP, ...EVA_ST_EVA_SP],
    states: [
      {
        id: "soku-button",
        name: "入力デバイス(即SP・ボタン)",
        trust: 18.7,
        reaches: EVA_ST_SOKU_SP,
        rate: { sakiel: 0.2, zeruel: 0.85 },
      },
      {
        id: "soku-lever",
        name: "入力デバイス(即SP・レバー)",
        trust: 83.5,
        reaches: EVA_ST_SOKU_SP,
        rate: { sakiel: 0.75, zeruel: 0.1 },
      },
      {
        id: "eva-button",
        name: "入力デバイス(エヴァ系・ボタン)",
        trust: 41.4,
        reaches: EVA_ST_EVA_SP,
        rate: { "st-sho": 0.4, "st-ni": 0.5, "st-zero": 0.55 },
      },
      {
        id: "eva-lever",
        name: "入力デバイス(エヴァ系・レバー)",
        trust: 84.3,
        reaches: EVA_ST_EVA_SP,
        rate: { "st-sho": 0.55, "st-ni": 0.45, "st-zero": 0.4 },
      },
      {
        id: "lever-heavy",
        name: "入力デバイス(レバーが重い)",
        trust: 100,
        rate: 0.025,
        text: "レバー抵抗",
      },
      {
        id: "lever-auto",
        name: "入力デバイス(自動引き込み)",
        trust: 100,
        rate: 0.025,
        text: "自動引き込み",
      },
    ],
  },
  {
    key: "launch",
    label: "SP発展演出",
    component: true,
    reaches: [...EVA_ST_EVA_SP, "dummy"],
    states: [
      { id: "three", name: "SP発展(3機発進)", trust: 58.9, rate: 0.75 },
      {
        id: "solo-zero",
        name: "SP発展(零号機単機)",
        trust: 80.7,
        reaches: ["st-zero"],
        rate: 0.2,
        text: "零号機 単機発進",
      },
      {
        id: "solo-ni",
        name: "SP発展(弐号機単機)",
        trust: 83.4,
        reaches: ["st-ni"],
        rate: 0.2,
        text: "弐号機 単機発進",
      },
      {
        id: "solo-sho",
        name: "SP発展(初号機単機)",
        trust: 90.0,
        reaches: ["st-sho", "dummy"],
        rate: 0.2,
        text: "初号機 単機発進",
      },
      {
        id: "launch-premium",
        name: "SP発展(プレミアム)",
        trust: 100,
        rate: 0.01,
        text: "プレミアム発進",
      },
    ],
  },
  {
    key: "shutter",
    label: "リーチ時シャッター",
    component: true,
    reaches: EVA_ST_SP,
    states: [
      {
        id: "shutter-normal",
        name: "シャッター(通常)",
        trust: 30.0,
        rate: 0.55,
      },
      {
        id: "shutter-red",
        name: "シャッター(赤)",
        trust: 73.4,
        rate: {
          sakiel: 0.25,
          zeruel: 0.05,
          "st-sho": 0.25,
          "st-ni": 0.2,
          "st-zero": 0.15,
          dummy: 0.25,
          mission: 0.1,
        },
        text: "赤シャッター",
      },
      {
        id: "shutter-gold",
        name: "シャッター(金)",
        trust: 94.3,
        rate: {
          sakiel: 0.08,
          zeruel: 0.01,
          "st-sho": 0.06,
          "st-ni": 0.04,
          "st-zero": 0.03,
          dummy: 0.08,
          mission: 0.02,
        },
        text: "金シャッター",
      },
      {
        id: "shutter-dummy",
        name: "シャッター(ダミープラグ)",
        trust: 78.8,
        reaches: ["dummy"],
        rate: 0.1,
        text: "ダミープラグ",
      },
    ],
  },
];
