// スロット機種 ハイエナ概算スペック（ゾーン期待値対応版）
// ----------------------------------------------------------------------------
// ceilingG       : 天井ゲーム数
// ceilingPayout  : 天井恩恵の平均獲得枚数
// gamePerMin     : 1分あたりの消化ゲーム数（省略時 13.3）
// zones          : ゾーン情報配列
//   startG       : ゾーン開始G（このG数から狙い始める）
//   endG         : ゾーン終了G（このG数まで滞在）
//   name         : ゾーン名
//   hitPct       : ゾーン滞在中のAT/ボーナス当選確率 (0.0〜1.0)
//   avgPayout    : 当選時の平均獲得枚数
//   note         : 備考
// ----------------------------------------------------------------------------
window.HYENA_SPECS = [
  {
    id: "hokuto-tensei2",
    name: "スマスロ 北斗の拳 転生の章2",
    ceilingG: 1536,
    ceilingPayout: 1500,
    gamePerMin: 13.3,
    note: "シャッターゾーン狙いが有名。AT後の即連も有効",
    zones: [
      {
        startG: 0,
        endG: 65,
        name: "AT後即連ゾーン",
        hitPct: 0.35,
        avgPayout: 1500,
        note: "AT後0〜65G。前回AT終了直後の台を狙う",
      },
      {
        startG: 193,
        endG: 256,
        name: "シャッターゾーン（最重要）",
        hitPct: 0.28,
        avgPayout: 1500,
        note: "全モード共通の最高当選帯。シャッター演出でモード判別可",
      },
      {
        startG: 385,
        endG: 448,
        name: "第2シャッターゾーン",
        hitPct: 0.18,
        avgPayout: 1500,
        note: "モードBCなら高期待度",
      },
      {
        startG: 577,
        endG: 640,
        name: "第3ゾーン",
        hitPct: 0.12,
        avgPayout: 1500,
        note: "モードC天井(576G)越え狙い",
      },
      {
        startG: 1400,
        endG: 1536,
        name: "天井前ゾーン",
        hitPct: 0.85,
        avgPayout: 1500,
        note: "天井136G前は実質ほぼ確定",
      },
    ],
  },
  {
    id: "toloveru-darkness",
    name: "L ToLOVEるダークネス",
    ceilingG: 999,
    ceilingPayout: 1200,
    gamePerMin: 13.3,
    note: "650Gゾーンが最強（当選率約40〜50%）",
    zones: [
      {
        startG: 140,
        endG: 160,
        name: "150Gゾーン",
        hitPct: 0.08,
        avgPayout: 1200,
        note: "軽いゾーン。他ゾーンとの複合狙い向き",
      },
      {
        startG: 240,
        endG: 260,
        name: "250Gゾーン",
        hitPct: 0.15,
        avgPayout: 1200,
        note: "チャンス目当選規定。ゾーン狙いの選択肢",
      },
      {
        startG: 440,
        endG: 460,
        name: "450Gゾーン",
        hitPct: 0.10,
        avgPayout: 1200,
        note: "発明品チャンス該当G数",
      },
      {
        startG: 630,
        endG: 670,
        name: "650Gゾーン（最重要）",
        hitPct: 0.45,
        avgPayout: 1200,
        note: "最強ゾーン。当選率約40〜50%。最も狙い目",
      },
      {
        startG: 900,
        endG: 999,
        name: "天井前ゾーン",
        hitPct: 0.75,
        avgPayout: 1200,
        note: "天井ST「楽園計画」濃厚",
      },
    ],
  },
  {
    id: "kabaneri-kaimon",
    name: "スマスロ カバネリ 海門決戦",
    ceilingG: 996,
    ceilingPayout: 1500,
    gamePerMin: 13.3,
    note: "周期システム。設定変更後は天井短縮で狙い目大",
    zones: [
      {
        startG: 0,
        endG: 150,
        name: "1周期目ゾーン",
        hitPct: 0.33,
        avgPayout: 1500,
        note: "全設定1周期目AT期待度約33%以上",
      },
      {
        startG: 260,
        endG: 320,
        name: "2周期目終盤ゾーン",
        hitPct: 0.25,
        avgPayout: 1500,
        note: "2周期目はモード判別のカギ",
      },
      {
        startG: 550,
        endG: 650,
        name: "4周期目ゾーン",
        hitPct: 0.20,
        avgPayout: 1500,
        note: "4周期超えで期待値が出始める",
      },
      {
        startG: 880,
        endG: 996,
        name: "天井前ゾーン",
        hitPct: 0.80,
        avgPayout: 1500,
        note: "天井エピソードボーナス濃厚",
      },
    ],
  },
  {
    id: "monkeyturn5",
    name: "スマスロ モンキーターンV",
    ceilingG: 795,
    ceilingPayout: 900,
    gamePerMin: 13.3,
    note: "周期天井最大6周期。モード別に期待度が大きく異なる",
    zones: [
      {
        startG: 0,
        endG: 80,
        name: "1周期目ゾーン",
        hitPct: 0.40,
        avgPayout: 900,
        note: "全設定1周期目AT期待度約40%。天国なら確定",
      },
      {
        startG: 160,
        endG: 230,
        name: "2周期目終盤ゾーン",
        hitPct: 0.20,
        avgPayout: 900,
        note: "通常A/Bはここが勝負。2周期目モード判別",
      },
      {
        startG: 490,
        endG: 580,
        name: "5周期目ゾーン",
        hitPct: 0.25,
        avgPayout: 900,
        note: "5周期以降は期待値プラスに転じやすい",
      },
      {
        startG: 700,
        endG: 795,
        name: "天井前ゾーン",
        hitPct: 0.80,
        avgPayout: 900,
        note: "天井AT当選確定",
      },
    ],
  },
  {
    id: "karakuri-circus",
    name: "Lパチスロ からくりサーカス",
    ceilingG: 1200,
    ceilingPayout: 1200,
    gamePerMin: 13.3,
    note: "CZ成功でAT。CZスルー4回で5回目AT確定",
    zones: [
      {
        startG: 60,
        endG: 80,
        name: "天国規定ゾーン",
        hitPct: 0.70,
        avgPayout: 1200,
        note: "天国モードなら70G平均で当選",
      },
      {
        startG: 260,
        endG: 310,
        name: "通常B規定ゾーン",
        hitPct: 0.22,
        avgPayout: 1200,
        note: "通常Bは550G平均。このゾーンがチャンス",
      },
      {
        startG: 500,
        endG: 600,
        name: "通常A/C規定ゾーン",
        hitPct: 0.18,
        avgPayout: 1200,
        note: "通常A/C(730G平均)の当選帯",
      },
      {
        startG: 1100,
        endG: 1200,
        name: "天井前ゾーン",
        hitPct: 0.85,
        avgPayout: 1200,
        note: "1100G以上ハマり→次回天井300G以内に短縮",
      },
    ],
  },
  {
    id: "kaguya",
    name: "Lパチスロ かぐや様は告らせたい",
    ceilingG: 1100,
    ceilingPayout: 1000,
    gamePerMin: 13.3,
    note: "CZスルー最大7回。BIG後650G〜がボーダー",
    zones: [
      {
        startG: 120,
        endG: 160,
        name: "130Gゾーン",
        hitPct: 0.12,
        avgPayout: 1000,
        note: "REG後に特に有効。CZスルー2回以上で期待値アップ",
      },
      {
        startG: 270,
        endG: 340,
        name: "300Gゾーン",
        hitPct: 0.15,
        avgPayout: 1000,
        note: "複数の規定G数ゾーンの一つ",
      },
      {
        startG: 560,
        endG: 650,
        name: "600Gゾーン（最重要）",
        hitPct: 0.22,
        avgPayout: 1000,
        note: "最重要ゾーン。BIG後650G〜が狙い目のボーダー",
      },
      {
        startG: 1000,
        endG: 1100,
        name: "天井前ゾーン",
        hitPct: 0.85,
        avgPayout: 1000,
        note: "BIG以上濃厚。残り100Gで期待値急上昇",
      },
    ],
  },
  {
    id: "valvrave2",
    name: "Lパチスロ革命機ヴァルヴレイヴ2",
    ceilingG: 1500,
    ceilingPayout: 1100,
    gamePerMin: 13.3,
    note: "複雑な周期システム。CZ間天井999Gも存在",
    zones: [
      {
        startG: 0,
        endG: 200,
        name: "1周期目ゾーン",
        hitPct: 0.20,
        avgPayout: 1100,
        note: "天国なら1周期で確定。通常Aは14%",
      },
      {
        startG: 580,
        endG: 700,
        name: "CZ間600Gゾーン",
        hitPct: 0.18,
        avgPayout: 1100,
        note: "CZ間天井(999G)狙いのボーダー付近",
      },
      {
        startG: 880,
        endG: 999,
        name: "CZ間天井前",
        hitPct: 0.75,
        avgPayout: 1100,
        note: "CZ間天井999G。ここから期待値プラス確定",
      },
      {
        startG: 1400,
        endG: 1500,
        name: "ボーナス間天井前",
        hitPct: 0.90,
        avgPayout: 1100,
        note: "ボーナス間天井1500G。革命ボーナス確定",
      },
    ],
  },
  {
    id: "godzilla-eva",
    name: "Lゴジラ対エヴァンゲリオン",
    ceilingG: 1000,
    ceilingPayout: 1050,
    gamePerMin: 13.3,
    note: "AT後70G引き戻し状態。ボーナス9スルーで天井",
    zones: [
      {
        startG: 0,
        endG: 70,
        name: "AT後引き戻しゾーン",
        hitPct: 0.45,
        avgPayout: 1050,
        note: "AT終了後70G間は高確率状態。赤い稲妻で判別",
      },
      {
        startG: 600,
        endG: 700,
        name: "640Gゾーン（ボーダー）",
        hitPct: 0.15,
        avgPayout: 1050,
        note: "等価で640G〜がハイエナボーダー",
      },
      {
        startG: 900,
        endG: 1000,
        name: "天井前ゾーン",
        hitPct: 0.80,
        avgPayout: 1050,
        note: "天井ボーナス確定。ゴジラボーナス7pt到達",
      },
    ],
  },
];
